use project;

ALTER TABLE all_player_stats_college
MODIFY COLUMN passing_completions INT,
MODIFY COLUMN passing_att INT,
MODIFY COLUMN passing_pct INT,
MODIFY COLUMN passing_yds INT,
MODIFY COLUMN passing_td INT,
MODIFY COLUMN passing_int INT,
MODIFY COLUMN rushing_car INT,
MODIFY COLUMN rushing_yds INT,
MODIFY COLUMN rushing_td INT,
MODIFY COLUMN rushing_long INT,
MODIFY COLUMN receiving_rec INT,
MODIFY COLUMN receiving_yds INT,
MODIFY COLUMN receiving_td INT,
MODIFY COLUMN receiving_long INT,
MODIFY COLUMN fumbles_fum INT,
MODIFY COLUMN fumbles_lost INT,
MODIFY COLUMN defensive_tot INT,
MODIFY COLUMN defensive_solo INT,
MODIFY COLUMN defensive_tfl INT,
MODIFY COLUMN defensive_sacks INT,
MODIFY COLUMN defensive_qb_hur INT,
MODIFY COLUMN interceptions_int INT,
MODIFY COLUMN interceptions_yds INT,
MODIFY COLUMN interceptions_td INT,
MODIFY COLUMN defensive_pd INT,
MODIFY COLUMN kicking_fgm INT,
MODIFY COLUMN kicking_fga INT,
MODIFY COLUMN kicking_xpa INT,
MODIFY COLUMN kicking_xpm INT,
MODIFY COLUMN kicking_pts INT,
MODIFY COLUMN kicking_long INT,
MODIFY COLUMN kick_returns_no INT,
MODIFY COLUMN kick_returns_yds INT,
MODIFY COLUMN kick_returns_td INT,
MODIFY COLUMN kick_returns_long INT,
MODIFY COLUMN punting_no INT,
MODIFY COLUMN punting_long INT,
MODIFY COLUMN punting_in_20 INT,
MODIFY COLUMN punting_tb INT,
MODIFY COLUMN punting_yds INT,
MODIFY COLUMN punt_returns_no INT,
MODIFY COLUMN punt_returns_yds INT,
MODIFY COLUMN punt_returns_td INT,
MODIFY COLUMN punt_returns_long INT;

ALTER TABLE all_player_stats_college
MODIFY COLUMN passing_ypa FLOAT,
MODIFY COLUMN rushing_ypc FLOAT,
MODIFY COLUMN receiving_ypr FLOAT,
MODIFY COLUMN interceptions_avg FLOAT,
MODIFY COLUMN kicking_pct FLOAT,
MODIFY COLUMN kick_returns_avg FLOAT,
MODIFY COLUMN punting_ypp FLOAT,
MODIFY COLUMN punt_returns_avg FLOAT;
